apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollout
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: main-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: argo-rollout
    spec:
      project: "default"
      syncPolicy: 
        automated: {}
      syncOptions:
      - CreateNamespace=true
      source:
        repoURL: https://github.com/azubuikeokom/k8s-flask-server.git
        targetRevision: HEAD
        path: apps/argo-rollout/install
      destination:
        server: '{{.url}}'
        namespace: argo-rollouts

