apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollout
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: main-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: argo-rollout
    spec:
      project: "default"
      syncPolicy: 
        automated: {}
      syncOptions:
      - CreateNamespace=true
      source:
      - chart: argo-rollouts
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.37.7
      destination:
        server: '{{.url}}'
        namespace: argo-rollouts

