apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-server
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/azubuikeokom/k8s-flask-server.git
      revision: HEAD
      directories:
      - path: flask-server/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/azubuikeokom/k8s-flask-server.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=false